sudo: required

services:
  - docker

before_install:
  - docker build -t elliotgonzalez/react-multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true elliotgonzalez/react-multi-test npm test

after_success:
  - docker build -t elliotgonzalez/multi-client ./client
  - docker build -t elliotgonzalez/multi-nginx ./nginx
  - docker build -t elliotgonzalez/multi-server ./server
  - docker build -t elliotgonzalez/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push elliotgonzalez/multi-client
  - docker push elliotgonzalez/multi-nginx
  - docker push elliotgonzalez/multi-server
  - docker push elliotgonzalez/multi-worker

deploy:
  provider: elasticbeanstalk
  regions: 'us-east-2'
  app: 'docker-react-multi'
  env: 'DockerReactMulti-env'
  bucket_name: 'elasticbeanstalk-us-east-2-622904791075'
  bucket_path: 'docker-react-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
